### ISSUE TITLE
"Start With SteamVR" doesn't work for "C:\Program Files\"

### ISSUE THREAD

**Issue by Allon-Guralnek** [benotter/TurnSignal#13] opened 2017-07-29 12:59 UTC
Version 2.1 of TurnSignal is a big improvement, well done!

I couldn't understand why "Start WIth SteamVR" option didn't work. I had to run it manually before SteamVR for it to appear. Because TurnSignal doesn't come with an installer, I unzipped it into "C:\Program Files\TurnSignal 2.1\". I thought that would be a reasonable place to put it. I made sure to "Unblock" it from being marked as a downloaded application. But "Start With SteamVR" wouldn't work (no error, just didn't start automatically), and when I start it manually it first gives me the following warning, even though I unblocked it:

![image](https://user-images.githubusercontent.com/1709453/28744958-a3915c64-7475-11e7-9a3d-67d3c68113ba.png)
_On Windows 10 Creator's Update_

So I suspected the location being an issue. I copied it to my desktop and ran it manually once from there (without getting the above warning) and then enabled "Start With SteamVR", existed SteamVR and reopened it, and now the auto-starting worked!

Not sure what the best solution would be - to fix it so that it works from any location, or to give an error that when trying to enable "Start with SteamVR" that explains where it can and cannot be placed. Probably the best solution would be to use an installer and auto-updater, like [Squirrel](https://github.com/Squirrel/Squirrel.Windows) (best solution for .NET apps afaik, but haven't had the pleasure of using it yet). Using Squirrel means it would pick a good installation folder on its own, and it would also mean you could release as many small updates as you want (which is a good things, aim for small iterations) without inconveniencing your users.

**Comment by benotter** [comment] 2017-07-29 21:34
Thanks for the report,

I can probably fix some of this issue up with cleaning up how the app is registered with OpenVR (it really needs it), so that it registers and keeps its location updated and consistent, but you are right, I need, like, an installer, or some common place for files to rest for an easy update.
 
I was thinking about how to deliver incremental updates, haven't fully checked out squirrel yet, but being its this is a unity app, not really sure how well that solution will work.

I think the initial failure with the auto-start may actually be because of the default option IS to auto-start with steam, and it ends up doing some weirdness where the UI tries to update prefs, which fires the registration with steamvr, but the timing is very wonky, and I have a lot of 'check-only-once' style setup functions to keep from running code every frame, that are probably causing issues.

**Comment by benotter** [comment] 2017-07-30 04:24
Hopefully fixed in #14 ! (and previous commits to master),
Safest bet would be to delete all other copies of TurnSignal, put it where you want it, launch SteamVR, then launch TurnSignal, and make sure 'Auto-Start' is enabled,
in 2.1.2, I 'completely' redid how it registers to steamvr, so now its actually using the manifest as intended, and setting its auto-start property, instead of adding or removing it on enable / disable.

**Closed as completed** 2017-07-30 23:32 UTC
Labels: bug
