### ISSUE TITLE
CPU usage at 24%

### ISSUE THREAD

**Issue by Rytharr** [benotter/TurnSignal#8] opened 2017-07-24 21:50 UTC
From the moment I start this up, it is at 24% CPU usage and stays there whether the vive is going or not. I am using a 8350 running 1.4

**Comment by benotter** [comment] 2017-07-25 00:04
Heya! Thanks for the feedback, noticing that as well during profiling, will do my best to see what the issue is, hopefully its (or is not) just unity being aggressive with its prioritizing, and its something easy to fix.

**Comment by benotter** [comment] 2017-07-27 06:55
(Hopefully) Fixed in 2.0! #9

**Closed as completed** 2017-07-27 06:56 UTC
Labels: bug
